# GMapping 参数配置
slam_gmapping:
    # 激光雷达参数
    scan_topic: "/scan"        # 激光雷达话题名
    maxRange: 30.0             # RPLiDAR S2 的最大探测范围 30 米
    maxUrange: 12.0            # 激光的最大可用范围，光束被裁剪至此值 12 米
    sigma: 0.05                # 激光测距噪声标准差
    lskip: 0                   # 跳过部分激光点，减少计算负担

    # 坐标系参数
    map_frame: "map"           # 地图坐标系
    odom_frame: "odom"         # 里程计坐标系
    base_frame: "base_link"    # 机器人底盘的坐标系

    # 地图更新和分辨率参数
    map_update_interval: 1.0   # 地图更新间隔时间
    throttle_scans: 5          # 每 5 次扫描处理一次
    xmin: -30.0                # 地图最小范围 X 轴
    ymin: -30.0                # 地图最小范围 Y 轴
    xmax: 30.0                 # 地图最大范围 X 轴
    ymax: 30.0                 # 地图最大范围 Y 轴
    delta: 0.05                # 地图分辨率 5 cm

    # 粒子滤波器参数
    particles: 50              # 粒子数量
    resampleThreshold: 0.5     # 重采样阈值

    # 扫描匹配参数
    lstep: 0.05                # 线性步长
    astep: 0.05                # 角度步长
    iterations: 5              # 最大迭代次数
    kernelSize: 1              # 内核大小

    # 机器人运动噪声参数
    srr: 0.02                  # 平移对平移的噪声
    srt: 0.02                  # 平移对旋转的噪声
    str: 0.01                  # 旋转对平移的噪声
    stt: 0.02                  # 旋转对旋转的噪声

    # 平移和旋转更新噪声参数
    lsigma: 0.075              # 平移噪声
    ogain: 3.0                 # 匹配权重增益
    minimumScore: 50           # 最小得分要求

    # 机器人移动更新条件
    linearUpdate: 0.5          # 机器人移动 0.5 米触发地图更新
    angularUpdate: 0.35      # 机器人旋转约 20 度触发地图更新
    temporalUpdate: -1.0       # 时间更新间隔设置为 -1 表示不强制时间更新

    # 粒子滤波器采样参数
    llsamplerange: 0.01        # 平移采样范围
    llsamplestep: 0.01         # 平移采样步长
    lasamplerange: 0.005       # 旋转采样范围
    lasamplestep: 0.005        # 旋转采样步长
