# AMCL 参数配置文件

# 基本设置
max_particles: 500        # 最大粒子数 (默认: 5000) - 增加以提高定位精度
min_particles: 100         # 最小粒子数 (默认: 100) - 增加以保持足够的采样
kld_err: 0.01              # KLD采样误差 (默认: 0.01) - 保持默认值以平衡精度和效率
kld_z: 0.99                # KLD采样置信度 (默认: 0.99) - 保持高置信度

# 更新阈值
update_min_d: 0.2        # 最小更新距离，单位：米 (默认: 0.2) - 降低以适应小型机器人
update_min_a: 0.2        # 最小更新角度，单位：弧度 (默认: π/6) - 降低以适应小型机器人

# 里程计模型参数
odom_model_type: "diff"    # 里程计模型类型 (默认: "diff") - 适用于差速驱动
odom_alpha1: 0.2           # 旋转运动引起的旋转误差 (默认: 0.2) - 保持默认值
odom_alpha2: 0.2           # 平移运动引起的旋转误差 (默认: 0.2) - 保持默认值
odom_alpha3: 0.2           # 平移运动引起的平移误差 (默认: 0.2) - 略微增加以反映轮式编码器误差
odom_alpha4: 0.2           # 旋转运动引起的平移误差 (默认: 0.2) - 保持默认值
odom_alpha5: 0.1           # 平移误差 (默认: 0.2) - 略微降低以反映较好的里程计性能

# 激光扫描参数
laser_max_beams: 180       # 每次扫描使用的最大激光束数 (默认: 30) - 增加以提高精度，但不超过硬件限制
laser_z_hit: 0.5          # "hit"的权重 (默认: 0.95) - 保持高权重以重视有效匹配
laser_z_short: 0.05        # "short"的权重 (默认: 0.1) - 降低以减少短距离测量的影响
laser_z_max: 0.05          # "max"的权重 (默认: 0.05) - 保持默认值
laser_z_rand: 0.5         # "random"的权重 (默认: 0.05) - 保持默认值
laser_sigma_hit: 0.2       # 测量噪声标准差 (默认: 0.2) - 降低以反映较高精度的激光雷达
laser_lambda_short: 0.1    # 短距离测量的指数衰减参数 (默认: 0.1) - 保持默认值
laser_likelihood_max_dist: 2.0  # 最大似然距离，单位：米 (默认: 2.0) - 保持默认值，适应工厂环境

# 全局定位参数
# global_frame_id: "map"     # 全局坐标系 (默认: "map") - 保持默认值
odom_frame_id: "odom"      # 里程计坐标系 (默认: "odom") - 保持默认值
base_frame_id: "base_link" # 机器人基座坐标系 (默认: "base_link") - 保持默认值
transform_tolerance: 1.0   # 变换容忍度，单位：秒 (默认: 0.1) - 增加以适应复杂环境

# 恢复参数
recovery_alpha_slow: 0.0   # 慢速恢复参数 (默认: 0.0) - 增加以改善长期定位稳定性
recovery_alpha_fast: 0.0   # 快速恢复参数 (默认: 0.0) - 增加以快速恢复定位

# 初始姿态估计
initial_pose_x: 0.0        # 初始 X 坐标 (默认: 0.0) - 根据实际部署位置调整
initial_pose_y: 0.0        # 初始 Y 坐标 (默认: 0.0) - 根据实际部署位置调整
initial_pose_a: 0.0        # 初始角度 (默认: 0.0) - 根据实际部署方向调整
initial_cov_xx: 0.25       # X 方向初始协方差 (默认: 0.25) - 保持默认值
initial_cov_yy: 0.25       # Y 方向初始协方差 (默认: 0.25) - 保持默认值
initial_cov_aa: 0.068      # 角度初始协方差 (默认: 0.068) - 保持默认值

# 其他参数
gui_publish_rate: -1.0     # GUI 发布率，单位：Hz (默认: -1.0) - 设置适当值以减少计算负担
save_pose_rate: 0.5        # 保存姿态的频率，单位：Hz (默认: 0.5) - 保持默认值
use_map_topic: false       # 是否使用地图话题 (默认: false) - 保持默认值
first_map_only: false      # 是否只使用第一次接收到的地图 (默认: false) - 保持默认值

# 激光模型类型
laser_model_type: "likelihood_field"  # 激光模型类型 (beam, likelihood_field, likelihood_field_prob，默认: "likelihood_field") - 使用似然场模型以提高效率

# 全局定位
global_localization_min_d: 0.5  # 全局定位最小距离，单位：米 (默认: 0.5) - 保持默认值
global_localization_min_a: 0.5  # 全局定位最小角度，单位：弧度 (默认: 0.5) - 保持默认值

# 重采样参数
resample_interval: 1       # 重采样间隔 (默认: 2) - 降低以增加重采样频率，提高响应性

# 选择性重采样
selective_resampling: false  # 是否使用选择性重采样 (默认: false) - 保持默认值

# 调试选项
tf_broadcast: true         # 是否广播 TF 变换 (默认: true) - 保持默认值