# 全局代价地图和局部代价地图的通用参数
 
obstacle_range: 3.0,  # 考虑障碍物的最大范围 [m]（默认值：2.5）
raytrace_range: 3.5,  # 清除空间的最大范围 [m]（默认值：3.0）

# 机器人描述
footprint: [
    [0.334, 0.289],   # 前左角
    [0.334, -0.289],  # 前右角
    [-0.334, -0.289], # 后右角
    [-0.334, 0.289]   # 后左角
]  # 默认值：[]（空数组，表示圆形机器人）

# 膨胀层参数
inflation_radius: 0.2,  # 障碍物膨胀半径 [m]（默认值：0.55）
cost_scaling_factor: 15.0,  # 用于计算膨胀区域代价的指数衰减因子（默认值：10.0），增大会降低代价

# 地图类型
# map_type: costmap  # 使用代价地图（默认值：costmap），该参数已经弃用

# 传感器数据处理
observation_sources: base_lidar  # 使用的传感器源（默认值：""）

# 激光雷达传感器参数
base_lidar:
    sensor_frame: laser  # 激光雷达的坐标系（默认值：""）
    data_type: LaserScan  # 数据类型（默认值：LaserScan）
    topic: /scan  # 激光雷达数据的话题（默认值：""）
    marking: true  # 是否标记障碍物（默认值：true）
    clearing: true  # 是否清除空间（默认值：true）
