DWAPlannerROS:
    # 机器人配置参数
    # X方向速度限制 - 考虑到实际运行安全，取最大值的90%
    max_vel_x: 1.5   # 最大 X 方向速度设为1.8 m/s（满速2.0的90%），单位：m/s (默认: 0.55)
    min_vel_x: 0.0   # 最小 X 方向速度（设为负数则允许后退），单位：m/s (默认: 0.0)
    acc_lim_x: 5.0   # X 方向加速度限制，单位：m/s^2 (默认: 2.5)

    # Y方向速度限制 - 差分驱动机器人为0
    max_vel_y: 0.0  # 最大 Y 方向速度，单位：m/s (默认: 0.1)，差分驱动机器人为 0
    min_vel_y: 0.0  # 最小 Y 方向速度，单位：m/s (默认: -0.1)，差分驱动机器人为 0
    acc_lim_y: 0.0  # Y 方向加速度限制，单位：m/s^2 (默认: 2.5)

    # 整体平移速度限制
    max_vel_trans: 1.5   # 最大平移速度，与max_vel_x保持一致，单位：m/s (默认: 0.55)
    min_vel_trans: 0.05   # 最小平移速度，保持小的最小速度以确保平滑启动，单位：m/s (默认: 0.1)

    # 角速度限制 - 考虑到实际运行安全，取最大值的50%
    max_vel_theta: 1.8     # 最大旋转速度设为2.0 rad/s（满速6.28的约30%），单位：rad/s (默认: 1.0)
    min_vel_theta: 0.24    # 最小旋转速度，保持较小的最小角速度，单位：rad/s (默认: 0.4)
    acc_lim_theta: 5.0     # 旋转加速度限制，单位：rad/s^2 (默认: 3.2)

    # 停止条件
    theta_stopped_vel: 0.01      # （ROS Wiki 未记录）旋转停止的阈值
    trans_stopped_vel: 0.01    # （ROS Wiki 未记录）平移停止的阈值

    # 目标容差
    xy_goal_tolerance: 0.15         # 到达目标点的XY平面容差，单位：m (默认: 0.1)
    yaw_goal_tolerance: 0.2         # 到达目标点的偏航角容差，单位：rad (默认: 0.1)
    latch_xy_goal_tolerance: true   # 是否锁定XY目标容差 (默认: false)

    # 前向模拟
    sim_time: 1.7  # 前向模拟时间，单位：s (默认: 1.7)
    sim_granularity: 0.025  # 模拟的粒度，即速度变化轨迹模拟的步长，单位：m (默认: 0.025)
    vx_samples: 25  # X方向速度采样点数 (默认: 3)
    vy_samples: 1   # Y方向速度采样点数 (默认: 10)
    vth_samples: 20  # 旋转速度采样点数 (默认: 20)

    # 轨迹评分
    # cost =
    #     path_distance_bias * (distance to path from the endpoint of the trajectory in meters)
    #     + goal_distance_bias * (distance to local goal from the endpoint of the trajectory in meters)
    #     + occdist_scale * (maximum obstacle cost along the trajectory in obstacle cost (0-254))
    path_distance_bias: 32.0  # 沿全局路径的偏向权重 (默认: 32.0)
    goal_distance_bias: 24.0  # 朝向目标点的偏向权重 (默认: 24.0)
    occdist_scale: 0.02   # 障碍物距离的缩放因子 (默认: 0.01)，降低障碍物代价的权重，让机器人更"大胆"
    forward_point_distance: 0.325  # 前向点距离，单位：m (默认: 0.325)
    stop_time_buffer: 0.2  # 停止时间缓冲，单位：s (默认: 0.2)
    scaling_speed: 0.25  # 缩放速度，单位：m/s (默认: 0.25)
    max_scaling_factor: 0.2  # 最大缩放因子 (默认: 0.2)

    # 振荡防止
    oscillation_reset_dist: 0.05  # 振荡重置距离，单位：m (默认: 0.05)
    oscillation_reset_angle: 0.2  # （ROS Wiki 未记录）振荡重置角度，单位：rad (默认: 0.2)

    # 辅助调试选项
    publish_traj_pc : true      # （ROS Wiki 未记录）是否在 RViz 里发布轨迹
    publish_cost_grid: true     # 是否在 RViz 里发布代价网格
    global_frame_id: odom       # （ROS Wiki 未记录）基础坐标系

    # Global Planner
    prune_plan: true  # 定义机器人沿路径移动时是否吃掉计划。如果设置为 true，则机器人越过这些点 1 米后，这些点将从计划末尾掉落。
