# global_costmap_params.yaml
# 全局代价地图参数

global_costmap:
    global_frame: map  # 全局代价地图的参考坐标系（默认值：map）
    robot_base_frame: base_link  # 机器人的基准坐标系（默认值：base_link）

    update_frequency: 1.0  # 地图更新频率 [Hz]（默认值：5.0）
    publish_frequency: 1.0  # 地图发布频率 [Hz]（默认值：0.0）
    transform_tolerance: 0.5  # TF转换的容忍时间 [s]（默认值：0.3）

    # 全局代价地图边界设定
    # width: 10.0
    # height: 10.0

    # 全局代价地图插件配置
    plugins:
        - {name: static_layer, type: "costmap_2d::StaticLayer"}  # 静态图层，负责处理全局静态地图
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"} # 障碍物图层，负责动态障碍物检测
        - {name: restricted_areas, type: "prohibition_areas_layer::ProhibitionAreasLayer"} # 禁区图层，用于处理禁区
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"} # 膨胀图层，用于增加障碍物的安全边界

    # 全局代价地图膨胀图层参数
    inflation_layer:
        enabled: true              # 启用膨胀图层
        inflation_radius: 0.2      # 障碍物膨胀半径 [m]（默认值：0.55）
        cost_scaling_factor: 20.0  # 用于计算膨胀区域代价的指数衰减因子（默认值：10.0），增大会降低代价，使代价值衰减更快，这很关键！
                                # 值越大，代价值衰减越快，机器人会更"大胆"地靠近障碍物
