# local_costmap_params.yaml
# 局部代价地图参数

local_costmap:
    # 基础配置
    global_frame: map                    # 代价地图的全局参考坐标系
    robot_base_frame: base_link          # 机器人的基准坐标系
    transform_tolerance: 0.5             # TF转换的最大容忍时间，单位：秒

    # 更新参数
    update_frequency: 5.0               # 代价地图更新频率，单位：Hz
    publish_frequency: 5.0              # 代价地图发布频率，单位：Hz

    # 地图窗口配置
    rolling_window: true                 # 使用跟随机器人移动的滚动窗口

    # 局部代价地图边界设定
    width: 4.0                          # 局部地图宽度，单位：米
    height: 4.5                         # 局部地图高度，单位：米

    # 局部代价地图插件配置
    plugins:
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}  # 障碍物图层
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}  # 膨胀图层

    # 局部代价地图膨胀图层参数
    inflation_layer:
        enabled: true              # 启用膨胀图层
        inflation_radius: 0.2      # 障碍物膨胀半径 [m]（默认值：0.55）
        cost_scaling_factor: 20.0  # 用于计算膨胀区域代价的指数衰减因子（默认值：10.0），增大会降低代价，使代价值衰减更快，这很关键！
                                # 值越大，代价值衰减越快，机器人会更"大胆"地靠近障碍物