# local_costmap_params.yaml
# 局部代价地图参数

local_costmap:
    # 基础配置
    global_frame: map                    # 代价地图的全局参考坐标系
    robot_base_frame: base_link          # 机器人的基准坐标系
    transform_tolerance: 0.5             # TF转换的最大容忍时间，单位：秒

    # 更新参数
    update_frequency: 10.0               # 代价地图更新频率，单位：Hz
    publish_frequency: 10.0              # 代价地图发布频率，单位：Hz

    # 地图窗口配置
    rolling_window: true                 # 使用跟随机器人移动的滚动窗口

    # 局部代价地图边界设定
    width: 4.0                          # 局部地图宽度，单位：米
    height: 4.5                         # 局部地图高度，单位：米

    # 局部代价地图插件配置
    plugins:
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}  # 障碍物图层
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}  # 膨胀图层
