TebLocalPlannerROS:

  # 车体轮廓
  footprint_model:      # 使用多边形来拟合机器人形状，反映真实的长方体轮廓
    type: "polygon"     # 选择多边形类型
    vertices: [         # 使用顶点定义机器人的长方体形状
      [0.334, 0.289],   # 前左角 (66.8 cm 长, 57.8 cm 宽 的一半)
      [0.334, -0.289],  # 前右角
      [-0.334, -0.289], # 后右角
      [-0.334, 0.289]   # 后左角
    ]

  # 机器人配置参数
  max_vel_x: 0.8  # 最大前进速度 [m/s] (默认: 0.4)
  max_vel_x_backwards: 0.2  # 最大后退速度 [m/s] (默认: 0.2)
  max_vel_theta: 0.8  # 最大旋转速度 [rad/s] (默认: 0.3)
  acc_lim_x: 0.3  # 最大前进加速度 [m/s^2] (默认: 0.5)
  acc_lim_theta: 0.3  # 最大角加速度 [rad/s^2] (默认: 0.5)
  min_turning_radius: 0.0  # 最小转弯半径，0表示能够原地旋转 [m] (默认: 0.0)
  wheelbase: 0.4643  # 轮距 [m] (默认: 1.0)
  cmd_angle_instead_rotvel: false  # 使用角速度命令 (默认: false)

  # 轨迹配置
  teb_autosize: True  # 自动调整轨迹大小 (默认: True)
  dt_ref: 0.4  # 期望的轨迹时间分辨率 [s] (默认: 0.3)
  dt_hysteresis: 0.1  # 时间分辨率的滞后 [s] (默认: 0.1)
  global_plan_overwrite_orientation: True  # 覆盖全局规划的方向 (默认: True)
  max_global_plan_lookahead_dist: 5.0  # 考虑全局规划的最大前瞻距离 [m] (默认: 3.0)
  force_reinit_new_goal_dist: 1.0  # 强制重新初始化的新目标距离 [m] (默认: 1.0)
  feasibility_check_no_poses: 2  # 每隔多少个姿态检查一次可行性 (默认: 4)
  publish_feedback: false  # 是否发布反馈信息 (默认: false)
  shrink_horizon_backup: true  # 在计算问题出现时允许缩小范围 (默认: true)
  allow_init_with_backwards_motion: false  # 允许后退初始化 (默认: false)
  exact_arc_length: false  # 精确计算弧长 (默认: false)
  shrink_horizon_min_duration: 10.0  # 最小收缩时间 [s] (默认: 10.0)

  # 障碍物参数
  min_obstacle_dist: 0.2  # 与障碍物的最小距离 [m] (默认: 0.5)
  include_costmap_obstacles: True  # 是否包含代价地图障碍物 (默认: True)
  costmap_obstacles_behind_robot_dist: 0.5  # 考虑机器人后方多远的障碍物 [m] (默认: 1.0)
  obstacle_poses_affected: 30  # 每个障碍物影响的姿态数 (默认: 30)
  inflation_dist: 0.3  # 障碍物膨胀距离 [m] (默认: 0.6)
  include_dynamic_obstacles: true  # 是否考虑动态障碍物 (默认: false)
  dynamic_obstacle_inflation_dist: 0.6  # 动态障碍物膨胀距离 [m] (默认: 0.6)
  legacy_obstacle_association: false  # 使用旧版障碍物关联 (默认: false)
  obstacle_association_force_inclusion_factor: 1.5  # 强制包含因子 (默认: 1.5)
  obstacle_association_cutoff_factor: 5.0  # 障碍物关联截断因子 (默认: 5.0)

  # 优化参数
  no_inner_iterations: 7  # 每次外循环的内部迭代次数 (默认: 5)
  no_outer_iterations: 5  # 外循环迭代次数 (默认: 4)
  optimization_activate: True  # 激活优化 (默认: True)
  optimization_verbose: False  # 优化过程是否详细输出 (默认: False)
  penalty_epsilon: 0.1  # 添加到惩罚函数的小常数 (默认: 0.1)
  weight_max_vel_x: 2.0  # 最大速度目标的权重 (默认: 2.0)
  weight_max_vel_theta: 1.0  # 最大角速度目标的权重 (默认: 1.0)
  weight_acc_lim_x: 2.0  # 加速度限制的权重 (默认: 1.0)
  weight_acc_lim_theta: 2.0  # 角加速度限制的权重 (默认: 1.0)
  weight_kinematics_nh: 1000.0  # 非完整运动学约束的权重 (默认: 1000.0)
  weight_kinematics_forward_drive: 1.0  # 向前行驶的权重 (默认: 1.0)
  weight_kinematics_turning_radius: 1.0  # 转弯半径的权重 (默认: 1.0)
  weight_optimaltime: 1.0  # 时间优化的权重 (默认: 1.0)
  weight_obstacle: 50.0  # 障碍物权重 (默认: 50.0)
  weight_dynamic_obstacle: 50.0  # 动态障碍物权重 (默认: 50.0)
  weight_viapoint: 1.0  # 经由点权重 (默认: 1.0)
  weight_adapt_factor: 2.0  # 自适应因子的权重 (默认: 2.0)
  weight_optimaltime_penalty_backward_driving: 5.0  # 后退行驶的时间惩罚权重 (默认: 1.0)

  # 路径执行参数
  min_samples: 3  # 最小采样点数 (默认: 3)
  max_samples: 50  # 最大采样点数 (默认: 50)

  # 规划器行为
  xy_goal_tolerance: 0.2  # 目标点的XY容差 [m] (默认: 0.2)
  yaw_goal_tolerance: 0.1  # 目标点的偏航角容差 [rad] (默认: 0.1)
  free_goal_vel: false  # 允许目标速度自由 (默认: false)
  complete_global_plan: true  # 完成整个全局规划 (默认: true)

  # Via点
  global_plan_viapoint_sep: 0.5  # 全局规划中via点的最小分离距离 [m] (默认: -0.1)
  via_points_ordered: False  # via点是否有序 (默认: False)

  # 可视化
  publish_feedback: false  # 是否发布优化反馈 (默认: false)
  visualize_with_time_as_z_axis_scale: false  # 使用时间作为Z轴可视化 (默认: false)

  # 杂项
  odom_topic: "odom"  # 里程计话题名称 (默认: "odom")
  map_frame: "map"  # 地图坐标系名称 (默认: "map")

  # 恢复行为
  shrink_horizon_backup: true  # 在失败时缩小规划范围 (默认: true)
  oscillation_recovery: true  # 检测和恢复振荡 (默认: true)

# 1.5 m/s 配置（注释掉）
#  max_vel_x: 1.5
#  acc_lim_x: 0.7
#  max_vel_theta: 1.5
#  acc_lim_theta: 0.7

# 2.0 m/s 配置（注释掉）
#  max_vel_x: 2.0
#  acc_lim_x: 1.0
#  max_vel_theta: 2.0
#  acc_lim_theta: 1.0